# Generated by Django 4.2.7 on 2023-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='task',
            field=models.ManyToManyField(related_name='categories', to='task.task'),
        ),
    ]
