# Generated by Django 4.2.7 on 2023-12-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='task',
            new_name='tasks',
        ),
    ]
