# Generated by Django 4.2.7 on 2023-12-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('category', '0003_rename_task_category_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tasks',
            field=models.ManyToManyField(default='', related_name='categories', to='task.task'),
        ),
    ]
